namespace :create_states do
  task states: :environment do
    
    states = [
    { name: "Aguascalientes", abreviature:	"Ags"},
    { name: "Baja California", abreviature: "BC"},
    { name: "Baja California Sur", abreviature: "BCS"}, 
    { name: "Campeche", abreviature:	"Camp"},
    { name: "Chiapas", abreviature:	"Chis"},
    { name: "Chihuahua", abreviature:	"Chih"},
    { name: "Coahuila", abreviature:	"Coah"},
    { name: "Colima", abreviature:	"Col"},
    { name: "Durango", abreviature:	"Dgo"},
    { name: "Guanajuato", abreviature:	"Gto"},
    { name: "Guerrero", abreviature:	"Gro"},
    { name: "Hidalgo", abreviature:	"Hgo"},
    { name: "Jalisco", abreviature:	"Jal"},
    { name: "Estado de México", abreviature:	"EdoMex"},	
    { name: "Michoacán", abreviature:	"Mich"},
    { name: "Morelos", abreviature:	"Mor"},
    { name: "Nayarit", abreviature:	"Nay"},
    { name: "Nuevo", abreviature: "León"},
    { name: "Oaxaca", abreviature:	"Oax"},
    { name: "Puebla", abreviature:	"Pue"},
    { name: "Querétaro", abreviature:	"Qro"},
    { name: "Quintana Roo", abreviature: "QRoo"},
    { name: "San Luis Potosí", abreviature: "SLP"},
    { name: "Sinaloa", abreviature:	"Sin"},
    { name: "Sonora", abreviature:	"Son"},
    { name: "Tabasco", abreviature:	"Tab"},
    { name: "Tamaulipas", abreviature:	"Tamps"},
    { name: "Tlaxcala", abreviature:	"Tlax"},
    { name: "Veracruz", abreviature:	"Ver"},	
    { name: "Yucatán", abreviature:	"Yuc"},	
    { name: "Zacatecas", abreviature:	"Zac"}]

    villages = [{ name: "Calvillo", state_name: "Aguascalientes"},
    { name: "Real de Asientos", state_name: "Aguascalientes"},
    { name: "San José de Gracia", state_name: "Aguascalientes"},
    { name: "Tecate", state_name: "Baja California"},
    { name: "Loreto", state_name: "Baja California Sur"},
    { name: "Palizada", state_name: "Campeche"},
    { name: "Chiapa de Corzo", state_name: "Chiapas"},
    { name: "Comitán", state_name: "Chiapas"},
    { name: "Palenque", state_name: "Chiapas"},
    { name: "San Cristóbal de las Casas", state_name: "Chiapas"},
    { name: "Batopilas", state_name: "Chihuahua"},
    { name: "Casas Grandes", state_name: "Chihuahua"},
    { name: "Creel", state_name: "Chihuahua"},
    { name: "Arteaga", state_name: "Coahuila"},
    { name: "Candela", state_name: "Coahuila"},
    { name: "Cuatrociénegas", state_name: "Coahuila"},
    { name: "Guerrero", state_name: "Coahuila"},
    { name: "Parras de la Fuente", state_name: "Coahuila"},
    { name: "Melchor Múzquiz", state_name: "Coahuila"},
    { name: "Viesca", state_name: "Coahuila"},
    { name: "Comala", state_name: "Colima"},
    { name: "Mapimí", state_name: "Durango"},
    { name: "Nombre de Dios", state_name: "Durango"},
    { name: "Comonfort", state_name: "Guanajuato"},
    { name: "Dolores Hidalgo", state_name: "Guanajuato"},
    { name: "Jalpa de Cánovas", state_name: "Guanajuato"},
    { name: "Mineral de Pozos", state_name: "Guanajuato"},
    { name: "Salvatierra", state_name: "Guanajuato"},
    { name: "Yuriria", state_name: "Guanajuato"},
    { name: "Taxco de Alarcón", state_name: "Guerrero"},
    { name: "Huasca de Ocampo", state_name: "Hidalgo"},
    { name: "Huichapan", state_name: "Hidalgo"},
    { name: "Mineral del Chico", state_name: "Hidalgo"},
    { name: "Real del Monte", state_name: "Hidalgo"},
    { name: "Tezocuautla", state_name: "Hidalgo"},
    { name: "Zimapán", state_name: "Hidalgo"},
    { name: "Lagos de Moreno", state_name: "Jalisco"},
    { name: "Mascota", state_name: "Jalisco"},
    { name: "Mazamitla", state_name: "Jalisco"},
    { name: "San Sebastián del Oeste", state_name: "Jalisco"},
    { name: "Talpa de Allende", state_name: "Jalisco"},
    { name: "Tapalpa", state_name: "Jalisco"},
    { name: "Tequila", state_name: "Jalisco"},
    { name: "Tlaquepaque", state_name: "Jalisco"},
    { name: "Aculco", state_name: "Estado de México"},
    { name: "El Oro", state_name: "Estado de México"},
    { name: "Ixtapan de la Sal", state_name: "Estado de México"},
    { name: "Malinalco", state_name: "Estado de México"},
    { name: "Metepec", state_name: "Estado de México"},
    { name: "Teotihuacán", state_name: "Estado de México"},
    { name: "Tepotzotlán", state_name: "Estado de México"},
    { name: "Valle de Bravo", state_name: "Estado de México"},
    { name: "Villa del Carbón", state_name: "Estado de México"},
    { name: "Angangueo", state_name: "Michoacán"},
    { name: "Cuitzeo", state_name: "Michoacán"},
    { name: "Jiquilpan", state_name: "Michoacán"},
    { name: "Pátzcuaro", state_name: "Michoacán"},
    { name: "Santa Clara del Cobre", state_name: "Michoacán"},
    { name: "Tacámbaro", state_name: "Michoacán"},
    { name: "Tlalpujahua", state_name: "Michoacán"},
    { name: "Tzintuzuntzán", state_name: "Michoacán"},
    { name: "Tepoztlán", state_name: "Morelos"},
    { name: "Tlayacapan", state_name: "Morelos"},
    { name: "Compostela", state_name: "Nayarit"},
    { name: "Jala", state_name: "Nayarit"},
    { name: "Sayulita", state_name: "Nayarit"},
    { name: "Bustamante", state_name: "Nuevo León"},
    { name: "Linares", state_name: "Nuevo León"},
    { name: "Santiago", state_name: "Nuevo León"},
    { name: "Calpulálpam", state_name: "Oaxaca"},
    { name: "Huautla de Jiménez", state_name: "Oaxaca"},
    { name: "Mazunte", state_name: "Oaxaca"},
    { name: "Mitla", state_name: "Oaxaca"},
    { name: "Teposcolula", state_name: "Oaxaca"},
    { name: "Atlixco", state_name: "Puebla"},
    { name: "Chignahuapan", state_name: "Puebla"},
    { name: "Cholula", state_name: "Puebla"},
    { name: "Cuetzalan", state_name: "Puebla"},
    { name: "Huachinango", state_name: "Puebla"},
    { name: "Pahuatlán del Valle", state_name: "Puebla"},
    { name: "Tlatlauquitepec", state_name: "Puebla"},
    { name: "Xicotepec de Juárez", state_name: "Puebla"},
    { name: "Zacatlán de las Manzanas", state_name: "Puebla"},
    { name: "Amealco", state_name: "Querétaro"},
    { name: "Bernal", state_name: "Querétaro"},
    { name: "Cadereyta", state_name: "Querétaro"},
    { name: "Jalpan de Serra", state_name: "Querétaro"},
    { name: "San Joaquín", state_name: "Querétaro"},
    { name: "Tequisquiapan", state_name: "Querétaro"},
    { name: "Bacalar", state_name: "Quintana Roo"},
    { name: "Isla" Mujeres, state_name: "Quintana Roo"},
    { name: "Tulum", state_name: "Quintana Roo"},
    { name: "Aquismón", state_name: "San Luis Potosí"},
    { name: "Real de Catorce", state_name: "San Luis Potosí"},
    { name: "Xilitla", state_name: "San Luis Potosí"},
    { name: "Cosalá", state_name: "Sinaloa"},
    { name: "El Fuerte", state_name: "Sinaloa"},
    { name: "El Rosario", state_name: "Sinaloa"},
    { name: "Mocorito", state_name: "Sinaloa"},
    { name: "Álamos", state_name: "Sonora"},
    { name: "Magdalena de Kino", state_name: "Sonora"},
    { name: "Tapijulapa", state_name: "Tabasco"},
    { name: "Mier", state_name: "Tamaulipas"},
    { name: "Tula", state_name: "Tamaulipas"},
    { name: "Huamantla", state_name: "Tlaxcala"},
    { name: "Tlaxco", state_name: "Tlaxcala"},
    { name: "Coatepec", state_name: "Veracruz"},
    { name: "Coscomatepec", state_name: "Veracruz"},
    { name: "Orizaba", state_name: "Veracruz"},
    { name: "Papantla", state_name: "Veracruz"},
    { name: "Xico", state_name: "Veracruz"},
    { name: "Zozocolco de Hidalgo", state_name: "Veracruz"},
    { name: "Izamal", state_name: "Yucatán"},
    { name: "Valladolid", state_name: "Yucatán"},
    { name: "Guadalupe", state_name: "Zacatecas"},
    { name: "Jerez", state_name: "Zacatecas"},
    { name: "Nochistlán", state_name: "Zacatecas"},
    { name: "Pinos", state_name: "Zacatecas"},
    { name: "Sombrerete", state_name: "Zacatecas"},
    { name: "Teúl de González Ortega", ,state_name: "Zacatecas"}]

    states.each do |state|
      s = State.new(name: state[:name], abreviature: state[:abreviature]) 
      s.save!
    end

  end
end